### PR TITLE
Fix characters rendering position; resolves #54

### LINKED ISSUE #54: Check if we render characters properly

### PR DESCRIPTION
**Pull request by neu5**

### CODE REVIEW

File: backend/index.js [hunk 1]
```diff
@@ -65,7 +65,7 @@ io.on("connection", (socket) => {
       });
 
       socket.emit("playerMoving", players);
-    }, 50);
+    }, 100);
```
Comment (przenz) [inline backend/index.js:68]: Let's avoid magic numbers and turn it into some constant.

File: src/scenes/GameScene.js [hunk 2]
```diff
@@ -166,7 +169,8 @@ export default class Game extends Phaser.Scene {
           motion: "idle",
           name: player.name,
           scene: this,
-          ...this.groundLayer.tileToWorldXY(player.x, player.y),
+          // we need to add 1 to X to render player in the right place
+          ...this.groundLayer.tileToWorldXY(player.x + 1, player.y),
```
Comment (przenz) [inline src/scenes/GameScene.js:173]: That's second time where this happens, should be probably wrapped into a separate function.

**Review by przenz — APPROVED** [review]
